---
version: "2"
run:
  modules-download-mode: vendor
  build-tags:
    - e2e
  timeout: 20m
linters:
  enable:
    - unused
    - errcheck
    - gomodguard
    - gosec
    - gocritic
    - revive
    - misspell
    - unconvert
  disable: []
  settings:
    errcheck:
      exclude-functions:
        - .errcheck.txt
  exclusions:
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: pkg/api/server/config/config.go
      - linters:
          - staticcheck
        path: pkg/api/server/v1alpha2/result/result.go
      - linters:
          - staticcheck
        path: pkg/api/server/v1alpha2/record/record.go
      - linters:
          - staticcheck
        path: pkg/api/server/v1alpha2/records_test.go
      - linters:
          - gocritic
          - gosec
        path: cmd/api/main.go
      - linters:
          - gocritic
          - staticcheck
        path: cmd/watcher/main.go
      - linters:
          - staticcheck
        path: pkg/watcher/logs/client.go
      - linters:
          - gosec
        path: pkg/internal/test/clients.go
      - linters:
          - gocritic
        path: pkg/api/server/cel2sql/type_coercion.go
      - linters:
          - staticcheck
        path: pkg/api/server/v1alpha2/results_test.go
      - linters:
          - staticcheck
        path: pkg/api/server/v1alpha2/results.go
      - linters:
          - staticcheck
        path: pkg/api/server/v1alpha2/records.go
      - linters:
          - staticcheck
          - revive
        path: pkg/api/server/cel2sql/interpreter.go
      - text: EXC0012
        linters:
          - revive
      - text: EXC0014
        linters:
          - revive
    paths:
      - vendor
      - tools
formatters:
  enable:
    - gofmt
    - goimports
