# Copyright 2021 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: results-release
spec:
  params:
  - default: https://github.com/tektoncd/results
    description: Repo URL to clone.
    name: repo
    type: string
  - default: main
    description: The Git revision to checkout.
    name: revision
    type: string
  - default: gcr.io/tekton-releases
    name: docker_repo
    type: string
  - description: GCS bucket/folder to upload configs
    name: bucket
    type: string
  - default: dev
    description: Version label to use for published images / configs
    name: version
    type: string
  - default: "true"
    description: If set to something other than "true", skip the build and test tasks
    name: runTests
    type: string
  tasks:
  - name: checkout
    params:
    - name: url
      value: $(params.repo)
    - name: revision
      value: $(params.revision)
    taskRef:
      params:
      - name: bundle
        value: ghcr.io/tektoncd/catalog/upstream/tasks/git-clone:0.7
      - name: name
        value: git-clone
      - name: kind
        value: task
      resolver: bundles
    workspaces:
    - name: output
      workspace: ws
  - name: unit-tests
    params:
    - name: package
      value: $(workspaces.source.path)/...
    runAfter:
    - checkout
    taskRef:
      params:
      - name: bundle
        value: ghcr.io/tektoncd/catalog/upstream/tasks/golang-test:0.2
      - name: name
        value: golang-test
      - name: kind
        value: task
      resolver: bundles
    when:
    - cel: '''$(params.runTests)'' == ''true'''
    workspaces:
    - name: source
      workspace: ws
  - name: publish-image-gcr
    params:
    - name: repo
      value: $(params.docker_repo)
    - name: tag
      value: $(params.version)
    runAfter:
    - unit-tests
    taskSpec:
      params:
      - description: Docker repository to publish to.
        name: repo
        type: string
      - default: latest
        name: tag
        type: string
      spec: null
      steps:
      - env:
        - name: KO_DOCKER_REPO
          value: $(params.repo)
        - name: KO_EXTRA_ARGS
          value: -P
        - name: RELEASE_VERSION
          value: $(params.tag)
        image: ghcr.io/tektoncd/plumbing/ko-gcloud@sha256:e3746b99c3269ae6db6ee615e42f51789f03cd0225276eede500cb5319a5dfb6
        name: publish
        script: |
          gcloud auth list
          gcloud auth configure-docker gcr.io,us-docker.pkg.dev

          $(workspaces.source.path)/release/release.sh
        workingDir: $(workspaces.source.path)
      workspaces:
      - name: source
    when:
    - cel: '''$(params.docker_repo)''.matches(''gcr.io/.*'')'
    workspaces:
    - name: source
      workspace: ws
  - name: publish-image
    params:
    - name: repo
      value: $(params.docker_repo)
    - name: githubRepo
      value: $(params.repo)
    - name: tag
      value: $(params.version)
    runAfter:
    - unit-tests
    taskSpec:
      params:
      - description: Docker repository to publish to.
        name: repo
        type: string
      - description: The source GitHub repo
        name: githubRepo
        type: string
      - default: latest
        name: tag
        type: string
      - default: ghcr.io
        name: imageRegistry
        type: string
      - default: tekton-robot
        name: imageRegistryUser
        type: string
      - default: credentials
        name: serviceAccountPath
        type: string
      spec: null
      stepTemplate:
        env:
        - name: CONTAINER_REGISTRY_CREDENTIALS
          value: $(workspaces.release-secret.path)/$(params.serviceAccountPath)
        - name: IMAGE_REGISTRY
          value: $(params.imageRegistry)
        - name: CONTAINER_REGISTRY_USER
          value: $(params.imageRegistryUser)
        - name: RELEASE_VERSION
          value: $(params.tag)
        - name: GITHUB_REPO
          value: $(params.githubRepo)
        - name: DOCKER_CONFIG
          value: /workspace/.docker
        - name: KO_EXTRA_ARGS
      steps:
      - image: cgr.dev/chainguard/crane:latest-dev@sha256:6fc6fcdeb173c7951f038e6a7b230f586c1be05a011d9e6f9db6c614ec412c2f
        name: container-registry-auth
        script: |
          #!/bin/sh
          set -ex

          if [ ! -f ${CONTAINER_REGISTRY_CREDENTIALS} ]; then
            echo "The release-secret workspace is required with ghcr.io"
            exit 1
          fi

          # Login to IMAGE_REGISTRY. Crane will honour DOCKER_CONFIG.
          cat ${CONTAINER_REGISTRY_CREDENTIALS} | \
            crane auth login -u ${CONTAINER_REGISTRY_USER} --password-stdin ${IMAGE_REGISTRY}
      - env:
        - name: KO_DOCKER_REPO
          value: $(params.repo)
        image: ghcr.io/tektoncd/plumbing/ko-gcloud@sha256:e3746b99c3269ae6db6ee615e42f51789f03cd0225276eede500cb5319a5dfb6
        name: publish
        script: |
          $(workspaces.source.path)/release/release.sh
        workingDir: $(workspaces.source.path)
      workspaces:
      - name: source
      - name: release-secret
        optional: true
    when:
    - cel: '!''$(params.docker_repo)''.matches(''gcr.io/.*'')'
    workspaces:
    - name: source
      workspace: ws
    - name: release-secret
      workspace: release-secret
  - name: publish-config
    params:
    - name: version
      value: $(params.version)
    - name: bucket
      value: $(params.bucket)
    runAfter:
    - publish-image
    taskSpec:
      params:
      - name: version
        type: string
      - name: bucket
        type: string
      spec: null
      steps:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: $(workspaces.gcp-secret.path)/release.json
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:310.0.0@sha256:cb03669fcdb9191d55a6200f2911fff3baec0b8c39b156d95b68aabe975ac506
        name: upload
        script: |
          gcloud auth activate-service-account --key-file=$(workspaces.gcp-secret.path)/release.json
          gcloud auth list
          gsutil cp $(workspaces.source.path)/release/release.yaml $(params.bucket)/previous/$(params.version)/release.yaml
          gsutil cp $(workspaces.source.path)/release/release.yaml $(params.bucket)/latest/release.yaml
          gsutil cp $(workspaces.source.path)/release/release_base.yaml $(params.bucket)/previous/$(params.version)/release_base.yaml
          gsutil cp $(workspaces.source.path)/release/release_base.yaml $(params.bucket)/latest/release_base.yaml
      workspaces:
      - name: source
      - name: gcp-secret
    workspaces:
    - name: source
      workspace: ws
    - name: gcp-secret
      workspace: gcp-secret
  workspaces:
  - name: ws
  - name: release-secret
  - name: gcp-secret
