# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: tekton-results-mysql
  namespace: tekton-pipelines
spec:
  ports:
    - port: 3306
  selector:
    app: tekton-results-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-mysql
  namespace: tekton-pipelines
spec:
  selector:
    matchLabels:
      app: tekton-results-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tekton-results-mysql
    spec:
      serviceAccountName: tekton-results-api
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: results
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tekton-results-mysql
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: results-mysql-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
