apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-watcher
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: tekton-results
    app.kubernetes.io/component: watcher
    pipeline.tekton.dev/release: "devel"
    version: "devel"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-results-watcher
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: tekton-results-watcher
        app.kubernetes.io/name: tekton-results
        app.kubernetes.io/component: watcher
        pipeline.tekton.dev/release: "devel"
        version: "devel"
    spec:
      serviceAccountName: tekton-pipelines-controller
      containers:
        - name: tekton-results-watcher
          image: ko://github.com/tektoncd/results/cmd/watcher
          args:
            [
              "-api_addr",
              "tekton-results-api-service.tekton-pipelines.svc.cluster.local:50051",
              "-auth_mode",
              "insecure",
            ]
