# Copyright 2021 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-results-api
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-results-api
rules:
  # Results API needs to be able to verify incoming auth tokens.
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  # Results API needs to be able to use RBAC to verify user authorization.
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-results-api
subjects:
  - kind: ServiceAccount
    name: tekton-results-api
    namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-results-api

---
apiVersion: v1
data:
  results.sql: "-- Copyright 2020 The Tekton Authors\n--\n-- Licensed under the Apache License, Version 2.0 (the \"License\");\n-- you may not use this file except in compliance with the License.\n-- You may obtain a copy of the License at\n--\n--      http://www.apache.org/licenses/LICENSE-2.0\n--\n-- Unless required by applicable law or agreed to in writing, software\n-- distributed under the License is distributed on an \"AS IS\" BASIS,\n-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n-- See the License for the specific language governing permissions and\n-- limitations under the License.\n\nCREATE TABLE results (\n\tparent varchar(64),\n\tid varchar(64),\n\n\tname varchar(64),\n\tannotations BLOB,\n\n\tcreated_time timestamp default current_timestamp not null,\n\tupdated_time timestamp default current_timestamp not null,\n\t\n\tetag varchar(128),\n\n\tPRIMARY KEY(parent, id)\n);\nCREATE UNIQUE INDEX results_by_name ON results(parent, name);\n\nCREATE TABLE records (\n\tparent varchar(64),\n\tresult_id varchar(64),\n\tid varchar(64),\n\n\tresult_name varchar(64),\n\tname varchar(64),\n\tdata BLOB,\n\n\tcreated_time timestamp default current_timestamp not null,\n\tupdated_time timestamp default current_timestamp not null,\n\n\tetag varchar(128),\n\n\tPRIMARY KEY(parent, result_id, id),\n\tFOREIGN KEY(parent, result_id) REFERENCES results(parent, id) ON DELETE CASCADE\n);\nCREATE UNIQUE INDEX records_by_name ON records(parent, result_name, name);\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-initdb-config
  namespace: tekton-pipelines

---
# Copyright 2021 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-results-watcher
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-results-watcher
rules:
  # Watcher needs to be able to create new and update existing results.
  - apiGroups: ["results.tekton.dev"]
    resources: ["results", "records"]
    verbs: ["create", "get", "update"]
  # Needed to read results and update annotations with Result ID.
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["get", "list", "patch", "update", "watch"]
  # We're not sure why global configmap access is needed, but the controller will
  # fail to start if it does not have this permission.
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-results-watcher
subjects:
  - kind: ServiceAccount
    name: tekton-results-watcher
    namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-results-watcher

---
# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results-mysql-pv-claim
  namespace: tekton-pipelines
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: tekton-results-mysql
  namespace: tekton-pipelines
spec:
  ports:
    - port: 3306
  selector:
    app: tekton-results-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-mysql
  namespace: tekton-pipelines
spec:
  selector:
    matchLabels:
      app: tekton-results-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tekton-results-mysql
    spec:
      serviceAccountName: tekton-results-api
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: results
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tekton-results-mysql
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: results-mysql-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config

---
# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-api
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: tekton-results
    app.kubernetes.io/component: api
    results.tekton.dev/release: "v0.1.0"
    version: "v0.1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-results-api
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: tekton-results-api
        app.kubernetes.io/name: tekton-results
        app.kubernetes.io/component: api
        results.tekton.dev/release: "v0.1.0"
        version: "v0.1.0"
    spec:
      serviceAccountName: tekton-results-api
      containers:
        - name: tekton-results-api
          image: gcr.io/tekton-releases/github.com/tektoncd/results/cmd/api:v0.1.0@sha256:f26349cc56fb63ca1b8094f0b3dc2cea70fee3f55a43170b17120917a0e204a8
          env:
            # See cmd/api/README.md for documentation of these vars.
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tekton-results-mysql
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tekton-results-mysql
                  key: password
            - name: DB_PROTOCOL
              value: tcp
            - name: DB_ADDR
              value: tekton-results-mysql.tekton-pipelines.svc.cluster.local
            - name: DB_NAME
              value: results
---
apiVersion: v1
kind: Service
metadata:
  name: tekton-results-api-service
  namespace: tekton-pipelines
spec:
  selector:
    app: tekton-results-api
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051

---
# Copyright 2020 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-results-watcher
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/name: tekton-results
    app.kubernetes.io/component: watcher
    results.tekton.dev/release: "v0.1.0"
    version: "v0.1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-results-watcher
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      labels:
        app: tekton-results-watcher
        app.kubernetes.io/name: tekton-results
        app.kubernetes.io/component: watcher
        results.tekton.dev/release: "v0.1.0"
        version: "v0.1.0"
    spec:
      serviceAccountName: tekton-results-watcher
      containers:
        - name: tekton-results-watcher
          image: gcr.io/tekton-releases/github.com/tektoncd/results/cmd/watcher:v0.1.0@sha256:ac246abff9299561bae42301fb5cae9e7b7f9e269ff08a05d85a46ea9fbf9aea
          args: ["-api_addr", "tekton-results-api-service.tekton-pipelines.svc.cluster.local:50051", "-auth_mode", "insecure"]

---
